### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by ramonskie** [Johnny-Knighten/ark-sa-server#24]
i tried many docker images and yours is the best documented.
but i can't seem to connect to my ark server.

i forwarded all the ports in my router., at one point i even put it in dmz mode

i tried it on my server and laptop the later one running the latest ubuntu, docker etc.
i double checked the port with `nc -z -v -u  MYPUBLICIP 8889` which mentioned it `port [udp/*] succeeded!`
and if i close the asa server it mentions it closed. so my assumption is that the connection if properly forwarded

i don't have a advanced setup like mentioned in the other issue.
and i run other services in docker and port forwarded. and these services work just fine.
as you can read i have no idea anymore where what to check
any help or suggestions would be appreciated

**Comment by Johnny-Knighten** [comment]
Here are a few things I would try and check:

1. Double and triple check your network config.
    * Sorry if you have tried all the stuff I'm about to list, but a configuration sanity check is always the easiest place to start.
    * Make sure the ports used by the docker container match your port forwarding and fire wall rules.
    * If your using all docker network defaults it should be in `bridge` mode and the container should share the IP of the cost it is running on.
    * Execute this to ensure the container ports are what you expect: `docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a`
    * Use a online port checker like https://portchecker.co/ to see if everything works end to end from a networking perspective
      * The `nc` command you used might not actually leaving you LAN segment. It might be hitting your router's IP table and get routed right back to the LAN. This is just speculation though.
    
 2.  Check if you can connect on the same LAN segment, ignore port forwarding and firewall rules for now.
   * Open ARK SA then open the console and use the `open IP:PORT`  command and see if connects
   *  Last time I checked the `open IP:PORT` did allow a password option, so remove the password from your server for this test.
   *  If you really want to remove most of the networking elements try to run the server and client on the same system and use `localhost/127.0.0.1` to connect to the server.

3. If you are trying to find the server via in the in-game server browser make sure you have the new `Show Player Servers` option checked.
  * This was added like a month ago so they can filter between Nitrado owned server and everyone else.
  * Also checkout a 3rd party site like https://www.battlemetrics.com/servers/arksa to see if they can see your server
    * With Battle Metric search via your public IP address
    
4. Check any networking specific features you may be using on your network.
    * I know you said your network setup is simple but check every feature you use
    * For instance, if your rely on a local DNS server verify its working correctly
    * Look at VLANs, Port Forwarding/ and Firewall Rules

Let me know if any of the things mentioned above helps your or at least point you in the right direction. If need be I can spin up a VM and try replicate your environment to the best of my ability.

**Comment by ramonskie** [comment]
thanks for the complete writeup. i did check all of your bulletpoints.
and i narrowed the problem a bit.
so it seems that ppl from outside my network can join the server perfectly fine.
but the playstation within the same network gets a timeout. so something strange is happening.
although i'm not sure what

**Comment by ramonskie** [comment]
okay i found a nasty little bug in my router when nat acceleration is enabled
thanks for your quick reply and help :)

for anyone who runs in to this see for more information:
https://www.snbforums.com/threads/no-nat-loopback-on-rt-ac68u-running-386-5-2.78893/
https://www.snbforums.com/threads/potential-bug-with-udp-nat-loopback-hairpinning.70892/page-2

**Comment by Johnny-Knighten** [comment]
Interesting, on the last release of the container the console versions of the game were not out yet. So I never had the chance to test the console release, but I also don't have any consoles to test with in the first place.

Are the other people joining your server also on a console?

Do you see any activity in the container log when other people join? How about when you try to join locally? What does the IP address look like when you join on the same LAN segment? Is it a private IP address or from the Docker network (172.x.x.x)?

I'm wondering if it has something to do with the networking players are joining from. When someone outside your network tries to join it will be obviously be represented by their public IP; however, when you try to join locally it the IP would be coming from a private RFC 1918 address (192.168.x.x, 10.x.x.x,...). Maybe there is something with how the server is advertised in the in-game browser?

**Comment by Johnny-Knighten** [comment]
You beat me to the reply lol.

Awesome! Glad your found the issue.

Let me know if we are good to close the issue, or if you want, feel free to close it yourself!

**Comment by ramonskie** [comment]
thanks for all the help so far.
and i hope more ppl will take a look after this repo.
as most of the others are not really feature complete to say it nicely

**Comment by Johnny-Knighten** [comment]
Thank you, I really strived to make a container that I personally was satisfied with!

If there are any other features you want/think I should implement just let me know.

I never actually advertised this container because most of my friends have already abandoned the game already. Although I'm not still actively developing new features I'm more than happy to help fix bugs and implement features if people request them.
